name: Test

on:
  push:
  pull_request:
  merge_group:

env: 
  CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}    

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-ci
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 20
        uses: actions/setup-node@v3
        with:
          node-version: 20
          # cache: "npm"
      - uses: szenius/set-timezone@v2.0
        name: Set Timezone
        with:
          timezoneLinux: "Europe/Berlin"
      - run: npm ci
      - run: npm run build
      - run: npx playwright install --with-deps
      - run: npm run test
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
      - name: Upload test results to Codecov
        if: ${{ !cancelled() }}
        uses: codecov/test-results-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}     
