name: Create Release
on:
  workflow_dispatch:
    inputs:
      version:
        description: "Version to promote"
        required: true
        default: "patch"

jobs:
  CreateRelease:
    runs-on: ubuntu-latest
    timeout-minutes: 180
    steps:
      - uses: actions/checkout@v4
        name: Checkout [Main]
        with:
          fetch-depth: 0
      - uses: volta-cli/action@v4
        with:
          package-json-path: "${{ github.workspace }}/package.json"
      - name: Use the package manager cache if available
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"
      - name: Install dependencies
        run: npm ci
      - name: Run commands in parallel
        run: |
          git config --global user.email 'max@smallstack.com'
          git config --global user.name 'Max Friedmann'
          npm run release:${{ github.event.inputs.version }}
